parameters:
    aws_profile: '%env(default::string:AWS_PROFILE)%'
    aws_region: '%env(default::string:AWS_REGION)%'

symfony_aws:
    sdk: ~

services:

    _defaults:
        autowire: true
        autoconfigure: true


    Palmyr\App\:
        resource: '../src/'
        exclude:
            - '../src/Application.php'
            - '../src/ShellCommand'

    property_accessor:
        class: Symfony\Component\PropertyAccess\PropertyAccess
        factory:
            - Symfony\Component\PropertyAccess\PropertyAccess
            - createPropertyAccessor
